.PHONY: clean All

All:
	@echo "----------Building project:[ TestProject - Release ]----------"
	@cd "TestProject" && "$(MAKE)" -f  "TestProject.mk"
clean:
	@echo "----------Cleaning project:[ TestProject - Release ]----------"
	@cd "TestProject" && "$(MAKE)" -f  "TestProject.mk" clean
